name: TestPulgin
version: '${project.version}'
main: com.luke.test.Main
api-version: 1.19
commands:
  test:
    description: This is a demo command.
    usage: /<command> [player]
    permission: <plugin name>.test
    permission-message: You don't have <permission>
  move:
